import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

import Footer from "@/components/common/Footer";
import Nav from "@/components/common/Nav";
import Providers from "./lib/Providers";

const notoSans = Noto_Sans({
  subsets: ["latin"],
  variable: "--font-noto-sans",
  weight: ["400", "600", "900"],
});
export const metadata: Metadata = {
  title: "리바이벌 | 세상의 모든 리뷰",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="font-sans">
      <body className={`${notoSans.variable} antialiased`}>
        <Providers>
          <Nav />
          <div className="min-h-[calc(100vh-8rem)]">{children}</div>
          <Footer />
          <div id="portal" />
        </Providers>
      </body>
    </html>
  );
}
